# Netlify Settings
[build]
  publish = "projects/current/printguys-redesign/development/frontend/"
  command = "echo 'No build process required for static site'"

# Redirect rules for clean URLs
[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/pages/contact.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/pages/blog.html"
  status = 200

# Service page redirects (for future expansion)
[[redirects]]
  from = "/services"
  to = "/pages/index.html#services"
  status = 302

[[redirects]]
  from = "/dtf-transfers"
  to = "/pages/index.html#services"
  status = 302

[[redirects]]
  from = "/screen-printing"
  to = "/pages/index.html#services"
  status = 302

[[redirects]]
  from = "/embroidery"
  to = "/pages/index.html#services"
  status = 302

[[redirects]]
  from = "/sublimation"
  to = "/pages/index.html#services"
  status = 302

[[redirects]]
  from = "/uv-stickers"
  to = "/pages/index.html#services"
  status = 302

# Quote and upload pages (placeholder redirects)
[[redirects]]
  from = "/quote"
  to = "/pages/contact.html"
  status = 302

[[redirects]]
  from = "/upload"
  to = "/pages/contact.html"
  status = 302

# 404 page
[[redirects]]
  from = "/*"
  to = "/pages/index.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com; img-src 'self' data: https:; font-src 'self' https:;"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"